modLoader="javafml" #mandatory
loaderVersion="[32,)"
license="MIT"
issueTrackerURL="https://github.com/unascribed/Ears/issues"
[[mods]]
modId="ears"
version="${file.jarVersion}"
displayName="Ears"
displayURL="https://ears.unascribed.com/"
logoFile="ears-icon.png"
authors="unascribed"
description="Faithful fancy fashion features for fuzzy folk."